# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# version: 2
# updates:
#     - package-ecosystem: "maven"
#     directory: "/"
#     schedule:
#       interval: "daily"
name: Dependabot

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      # Dependabot is included as a separate GitHub Action
      - name: Dependabot
        uses: github/dependabot-action/setup@v2
        with:
          # Specify the package manager (e.g., maven)
          package-manager: maven
   
