version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:35"
      timezone: "Asia/Kolkata"
    target-branch: "master"
    commit-message:
      prefix: "maven"
on:
  schedule:
    -cron : '35 12 * *'

#jobs:
#  dependabot:
#    runs-on: ubuntu-latest
#    steps:
#      -name: Checkout Repository
#      uses: actions/checkout@v2
#
#      - name: Set up JDK
#      uses: actions/setup-java@v2
#              with:
#                distribution: 'adopt'
#                java-version: '11'

